title: "xmonad - the tiling window manager that rocks"
twitter:
  username: xmonad
logo: images/xmonad-logo.png

theme: null

titles_from_headings:
  strip_title: true
  collections: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
