url: "https://xmonad.org"
title: "xmonad - the tiling window manager that rocks"

theme: null

titles_from_headings:
  strip_title: true
  collections: true

plugins:
  - jekyll-feed

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
