name: Check for broken links

on:
  workflow_dispatch:
  schedule:
    # Run every weekend
    - cron: '0 2 * * 6'

jobs:
  # internal and external links and anchors
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: liskin/gh-linkchecker@v0.1.0
        with:
          retries: 3

          linkcheckerrc: |
            [filtering]
            checkextern=1

            [AnchorCheck]

          custom-jq-filter-post: |
            def git_line_anchors:
                is_warning
                and (.urlname | (contains("//github.com/") or contains("//gitlab.")))
                and (.urlname | contains("#L"))
                and (.warning | startswith("Anchor"));
            # def git_line_anchors_to_info: if git_line_anchors then to_info end;
            def git_line_anchors_to_info: .;

            def moved_permanently_to_error:
                if is_warning and (.warning | contains("status: 301 ")) then
                    to_error
                end;

            def moved_temporarily_to_info:
                if is_warning and (.warning | contains("status: 302 ")) then
                    to_info
                end;

            def skip_rules:
                false;

            map(
                if skip_rules then
                    .
                else
                    moved_permanently_to_error |
                    moved_temporarily_to_info |
                    git_line_anchors_to_info
                end
            )

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
